ALTER TABLE public.actas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.acta_participantes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.acta_acuerdos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.acta_temas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.acta_firmas DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.acta_adjuntos DISABLE ROW LEVEL SECURITY;
